In [4]:
customers={"CUST_ID":[1001,1002,1003,1004,1005,1006,1007,1008,1009,1010],
           "CUST_NAME":["SURESH","RITHUN","soooaj","Raajil","irfan","jibin","Sumit","pratik","farook","akhil"],
           "ACC_TYPE":["savings","savings","savings","current","current","fixed","fixed","currrent","savings","current"],
           "RISK_SCORE":[1,4,3,5,3,2,4,3,3,5]
    }
customers
pd.DataFrame(customers)

   CUST_ID CUST_NAME  ACC_TYPE  RISK_SCORE
0     1001    SURESH   savings           1
1     1002    RITHUN   savings           4
2     1003    soooaj   savings           3
3     1004    Raajil   current           5
4     1005     irfan   current           3
5     1006     jibin     fixed           2
6     1007     Sumit     fixed           4
7     1008    pratik  currrent           3
8     1009    farook   savings           3
9     1010     akhil   current           5

In [3]:
import pandas as pd

In [5]:
transactions={"TXN_ID":["TXN_101","TXN_102","TXN_103","TXN_104","TXN_105","TXN_106","TXN_107","TXN_108","TXN_109","TXN_110"],
              "CUST_ID":[1001,1004,1003,1001,1005,1003,1007,1007,1008,1008],
              "TXN_TYPE":["deposit","withdrawl","transaction","withdrawl","transaction","deposit","treansaction","withdrawl","deposit","transaction"],
              "TXN_AMOUNT":[12000,3000,4500,7000,20000,2000,25000,10000,27000,17000],
              "TXN_DATES":["12-06-26","11-06-26","14-06-26","13-06-26","17-06-26","14-06-26","09-06-26","12-06-26","10-06-26","15-06-26"],
             }
pd.DataFrame(transactions)

    TXN_ID  CUST_ID      TXN_TYPE  TXN_AMOUNT TXN_DATES
0  TXN_101     1001       deposit       12000  12-06-26
1  TXN_102     1004     withdrawl        3000  11-06-26
2  TXN_103     1003   transaction        4500  14-06-26
3  TXN_104     1001     withdrawl        7000  13-06-26
4  TXN_105     1005   transaction       20000  17-06-26
5  TXN_106     1003       deposit        2000  14-06-26
6  TXN_107     1007  treansaction       25000  09-06-26
7  TXN_108     1007     withdrawl       10000  12-06-26
8  TXN_109     1008       deposit       27000  10-06-26
9  TXN_110     1008   transaction       17000  15-06-26

In [10]:
customers_raw.csv

NameError: name 'customers_raw' is not defined

In [12]:
df_customers=pd.DataFrame(customers)

In [14]:
df_customers.to_csv("customers_raw.csv",index=False)

In [15]:
df_transactions=pd.DataFrame(transactions)

In [16]:
df_transactions.to_csv("transactions_raw.csv",index=False)

In [19]:
import pandas as pd 
import random

In [39]:
fname=["sumit ","pratik ","suresh","irfan","Rithun","Sooraj","farok","raajil","akhil","rakshi"]
lname=["mj","br","S","C","cs","tm","cp","ts","J","muhamad"]
cust_id = []
cust_name = []
acc_type = []
risk_score = []
for i in range(100):
    unique_id = 1001+ i
    cust_id.append(unique_id)

    random_name = f"{random.choice(fname)}{random.choice(lname)}"
    
    if i % 10 == 0:
        cust_name.append(f"customer_{unique_id}")
    else:
        cust_name.append(f"Customer_{unique_id}")
    acc_type.append(random.choice(["savings","current","fixed"]))
    risk_score.append(random.randint(1,5))

In [43]:
ncustomers={
    "CUST_ID":cust_id,
    "CUT_NAME":cust_name,
    "ACC_TYPE":acc_type,
    "RISK_SCORE":risk_score
}
df_ncustomers=pd.DataFrame(ncustomers)

In [47]:
ncustomers=pd.DataFrame(ncustomers)
ncustomers

    CUST_ID       CUT_NAME ACC_TYPE  RISK_SCORE
0      1001  customer_1001    fixed           1
1      1002  Customer_1002  current           1
2      1003  Customer_1003  current           3
3      1004  Customer_1004  current           2
4      1005  Customer_1005  savings           1
..      ...            ...      ...         ...
95     1096  Customer_1096  savings           4
96     1097  Customer_1097  savings           4
97     1098  Customer_1098  savings           4
98     1099  Customer_1099  current           4
99     1100  Customer_1100  savings           2

[100 rows x 4 columns]

In [2]:
## Final customers ----- 

import pandas as pd
import random

fname = ["sumit", "pratik", "suresh", "irfan", "Rithun", "Sooraj", "farok", "raajil", "akhil", "rakshi"]
lname = ["mj", "br", "S", "C", "cs", "tm", "cp", "ts", "J", "muhamad"]

cust_id = []
cust_name = []
acc_type = []
risk_score = []

for i in range(1000):
    unique_id = 1001 + i
    cust_id.append(unique_id)

    # FIXED: Added the 'f', corrected the spelling to 'choice', and added a space between names
    random_name = f"{random.choice(fname)} {random.choice(lname)}"
    
    # FIXED: Kept only this name logic block, removed the old generic "Customer_1001" block
    if i % 10 == 0:
        cust_name.append(random_name.lower())
    else:
        cust_name.append(random_name)
        
    acc_type.append(random.choice(["savings", "current", "fixed"]))
    risk_score.append(random.randint(1, 5))

# Pack into dictionary
lcustomers = {
    "CUST_ID": cust_id,
    "CUST_NAME": cust_name,
    "ACC_TYPE": acc_type,
    "RISK_SCORE": risk_score
}

# Convert and display
#lcustomers = pd.DataFrame(lcustomers)
 # Displaying 12 rows so you can see the 0th and 10th row anomaly!

In [4]:
lcustomers = pd.DataFrame(lcustomers)
lcustomers

     CUST_ID       CUST_NAME ACC_TYPE  RISK_SCORE
0       1001       pratik br  savings           5
1       1002       Sooraj tm    fixed           1
2       1003        farok ts  savings           3
3       1004        akhil ts    fixed           1
4       1005        raajil C    fixed           3
..       ...             ...      ...         ...
995     1996        farok tm  current           1
996     1997        akhil br  current           5
997     1998  suresh muhamad  savings           4
998     1999         akhil J    fixed           1
999     2000   akhil muhamad    fixed           1

[1000 rows x 4 columns]

In [5]:
lcustomers.to_csv("lcustomers_raw.csv",index=False)

In [6]:
# final Transactions----


txn_id =[]
cust_id_txn =[]
txn_type = []
txn_amount = []
txn_dates = []

for i in range (5000): 
    txn_id.append(f"TXN_{2001 + i}")

    cust_id_txn.append(random.randint(1001,1100))

    txn_type.append(random.choice(["deposit","withdrawl","transfer"]))

    txn_amount.append(random.randint(1000,55000))

    txn_dates.append(f"2026-06-{random.randint(1,17)}")

ltransactions={
    "TXN_ID" : txn_id,
    "CUST_ID" : cust_id_txn,
    "TXN_TYPE" : txn_type,
    "TXN_AMOUNT" : txn_amount,
    "TXN_DATES" : txn_dates
}

In [7]:
ltransactions = pd.DataFrame(ltransactions)

In [8]:
ltransactions

        TXN_ID  CUST_ID   TXN_TYPE  TXN_AMOUNT   TXN_DATES
0     TXN_2001     1048   transfer       44959  2026-06-16
1     TXN_2002     1029    deposit        2430  2026-06-16
2     TXN_2003     1041    deposit       28897  2026-06-10
3     TXN_2004     1007  withdrawl       30848  2026-06-13
4     TXN_2005     1098    deposit       46601  2026-06-17
...        ...      ...        ...         ...         ...
4995  TXN_6996     1011  withdrawl       32265  2026-06-14
4996  TXN_6997     1041    deposit        7374   2026-06-4
4997  TXN_6998     1100  withdrawl       13766   2026-06-9
4998  TXN_6999     1075   transfer       19770  2026-06-12
4999  TXN_7000     1100   transfer       43782  2026-06-10

[5000 rows x 5 columns]

In [9]:
ltransactions.tail()

        TXN_ID  CUST_ID   TXN_TYPE  TXN_AMOUNT   TXN_DATES
4995  TXN_6996     1011  withdrawl       32265  2026-06-14
4996  TXN_6997     1041    deposit        7374   2026-06-4
4997  TXN_6998     1100  withdrawl       13766   2026-06-9
4998  TXN_6999     1075   transfer       19770  2026-06-12
4999  TXN_7000     1100   transfer       43782  2026-06-10

In [10]:
ltransactions.to_csv("ltransactions_raw.csv",index=False)